<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleName = 'Swifty Theme For Magento';
$moduleVersion = '1.0.0';
$moduleRevision = '1d730c4f83506db842744a50e09cf40340f38a44';
$moduleWikiUrl = 'http://www.docs.modulesgarden.com/';