<div id="features-container">
<?php $featured_products = $this->getProducts(); ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php if (($featured_products = $this->getProducts()) && $featured_products->getSize()): ?>
    <?php $featured_products = $featured_products->getItems() ?>
<?php shuffle($featured_products); ?>
    <div class="box recently">
        <div class="page-title catalog_title"><h2><?php echo $this->__('Featured Products') ?></h2></div>
        <div class="customNavigation">
            <a class="btn prev1"></a>
            <a class="btn next1"></a>
        </div>
        <br class="clear"/>
        <div class="listing-type-grid  catalog-listing">
            <?php $_collectionSize = count($featured_products) ?>
            <div id="owl-featured" class="owl-carousel-features owl-carousel products-grid">
                <?php
                    $i=0;
                    foreach ($featured_products as $_product): ?>
                        <?php $_columnCount = 20; ?>

                        <?php if ($i++%3==0): ?><?php endif ?>
                        <div class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                            <div>
                                <div class="product_img_container">
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                         <?php if($_product->getMgIsNew()) { ?>
                                            <div class="new-product"><?php echo $this->__('NEW') ?></div>
                                        <?php } ?>
                                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(277); ?>" width="277" height="277" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                                    <a href="<?php echo $_product->getProductUrl() ?>" class="hover view-more"><?php echo $this->__('View product') ?></a>
                                </div>
                            </div>
                            <div class="gird_prod_desc">
                                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>

                                <?php echo $this->getPriceHtml($_product, true) ?>
                                <div class="actions">
                                    <?php if($_product->isSaleable()): ?>
                                    <a class="btn-cart hover" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></a>
                                    <?php else: ?>
                                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                            <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="wishlist-icon hover"></a>
                                    <?php endif; ?>
                                    <ul class="add-to-links">
                                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                            <li><a href="<?php echo $_compareUrl ?>" class="compare-icon hover"></a></li>
                                        <?php endif; ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <?php if ($i%3==0 && $i!=$_collectionSize): ?><?php endif ?>
                    <?php endforeach ?>
            </div>
        </div>
    </div>
<?php endif; ?>
</div>
<br class="clear"/>